//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLExtensions.Controls.Layers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLExtensions.Controls.Layers.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataTemplate 
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:slec=&quot;clr-namespace:SLExtensions.Controls;assembly=SLExtensions.Controls&quot;
        ///    xmlns:local=&quot;clr-namespace:SLExtensions.Controls.Layers;assembly=SLExtensions.Controls&quot;    
        ///    xmlns:controls2=&quot;clr-namespace:System.Windows.Controls;assembly=System.Windows&quot;
        ///    &gt;
        ///    &lt;local:LayerItem Width=&quot;{Binding Path=Width}&quot; Height=&quot;{Binding Path=Height}&quot; Canvas.Lef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GLayersDataTemplate {
            get {
                return ResourceManager.GetString("GLayersDataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataTemplate 
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:slec=&quot;clr-namespace:SLExtensions.Controls;assembly=SLExtensions.Controls&quot;
        ///    xmlns:local=&quot;clr-namespace:SLExtensions.Controls.Layers;assembly=SLExtensions.Controls&quot;        
        ///    xmlns:controls2=&quot;clr-namespace:System.Windows.Controls;assembly=System.Windows&quot;
        ///    &gt;
        ///    &lt;local:LayerItem Width=&quot;{Binding Path=Width}&quot; Height=&quot;{Binding Path=Height}&quot; Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VELayersDataTemplate {
            get {
                return ResourceManager.GetString("VELayersDataTemplate", resourceCulture);
            }
        }
    }
}
