//*@@@*************************************************************************
//
// Microsoft Expression Encoder
// Copyright © Microsoft Corporation. All rights reserved.
//
//*@@@*************************************************************************
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Logging.Tracer.#Text")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Logging.Tracer.#MaxMemoryCapacity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Logging.Tracer.#MaxMemoryCapacity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.SlidingWindow.#IsSlowIncreasing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.SlidingWindow.#IsSlowDecreasing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.SlidingWindow.#IsIncreasing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.SlidingWindow.#IsFastIncreasing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Network.NetworkMediaInfo.#LockedBitRate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Network.NetworkMediaInfo.#BitrateValidation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#RelativeContentDownloadSpeedSeek")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#RelativeContentDownloadSpeed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#NetHeuristicsVersion")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#NetHeuristicsLogVersion")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#DownloadBandwidthFraction")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#BufferingSlopeThreshold")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#BufferFullnessFraction")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Heuristic.NetworkHeuristicsParams.#AbsoluteHighBandwidth")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#ParseConfigAssembly()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#OpenConfigUrlAsync()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#OpenConfigAssembly()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#LoadFromUrl(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#LoadFromAssembly(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ConfigurationLoader.#IsConfigurationAllowed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Streams.#MaxStreams")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Streams.#MaxDownloadQueue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Streams.#MaxBitratesPerStream")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration.#MajorVersion")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Heuristics+Network.#MinBitrate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Heuristics+Network.#MaxBitrate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.BitrateInfo.#StreamIndex")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.BitrateInfo.#IsBitrateSupported")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource+PlaybackInfo.#RenderedFramesPerSecond")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource+PlaybackInfo.#IsPausedOrStopped")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource+PlaybackInfo.#IsMinimizedBrowser")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource+PlaybackInfo.#DroppedFramesPerSecond")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.UIDispatcher.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Logging.Tracer.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Drm", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.GetFrameData.#DrmData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.StreamInfo.#BaseUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1055:UriReturnValuesShouldNotBeStrings", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.IUrlGenerator.#GenerateUrlStringForChunk(System.String,System.Int32,System.Int32,System.UInt64,System.Int64,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.IUrlGenerator.#GenerateUrlStringForChunk(System.String,System.Int32,System.Int32,System.UInt64,System.Int64,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.StreamInfo.#.ctor(System.String,System.String,System.Int32,System.Windows.Media.MediaStreamType,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.ChunkParserException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.ChunkNotParsedException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.BandwidthCalculator.#GetLastCalculation()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.IChunkParser.#GetFrame()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource.#DoSample(Microsoft.Expression.Encoder.AdaptiveStreaming.AdaptiveStreamingSource+WorkQueueElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Parsing.FragmentedMp4ParserImpl.#ParseHeader(System.IO.Stream)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.Expression.Encoder.AdaptiveStreaming.GetFrameData.#DrmData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Manifest.ManifestParserImpl.#ParseStreamInfo(System.Xml.XmlReader,System.Int32,System.String,Microsoft.Expression.Encoder.AdaptiveStreaming.ManifestInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "MS.Internal.Expression.Encoder.AdaptiveStreaming.Utilities.Configuration+Heuristics+FrameRate.#.cctor()")]
